### ISSUE TITLE
`DEP0005`: `Buffer()` is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by Neved4** [exsitu-projects/ilatex#3]
That function was deprecated as per https://github.com/nodejs/node/issues/4660.

While manually installing the extension, the following warning appears:
```sh
code --install-extension ilatex.vsix
Installing extensions...
(node:46741) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues.
Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Electron --trace-deprecation ...` to show where the warning was created)
Extension 'ilatex.vsix' was successfully installed.
```

With `--trace-deprecation` we can locate where the deprecated function is being used:
```NODE_OPTIONS="--trace-deprecation" code --install-extension ilatex.vsix 
Installing extensions...
(node:47479) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues.
Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (node:buffer:191:11)
    at new Buffer (node:buffer:275:3)
    at /Visual Studio Code.app/Contents/Resources/app/node_modules.asar/fd-slicer/index.js:109:18
    at pendGo (/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/pend/index.js:54:3)
    at onCb (/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/pend/index.js:41:7)
    at /Visual Studio Code.app/Contents/Resources/app/node_modules.asar/fd-slicer/index.js:31:7
    at FSReqCallback.wrapper [as oncomplete] (node:fs:677:5)
Extension 'ilatex.vsix' was successfully installed.
```

The following is the line that's causing this:
https://github.com/exsitu-projects/ilatex/blob/822b5900cbed0757c930fd549c3f25c8cc6d86bc/src/webview/template/static/js/pdf.js#L21298

To achieve the migration, we need to change its syntax:
```js
new Buffer(string)   // Old
Buffer.from(string)  // New
```

In the codebase:
```diff
-input = new Buffer(literals);
+input = Buffer.from(literals);
```

***

Additionally, `i-LaTeX` is using version `2.3.200` of `pdf.js`:
https://github.com/exsitu-projects/ilatex/blob/822b5900cbed0757c930fd549c3f25c8cc6d86bc/src/webview/template/static/js/pdf.js#L127
Last release of `pdf.js` currently is [3.9.179](https://github.com/mozilla/pdf.js/releases/tag/v3.9.179) and lacks this issue, so upgrading the dependency is another option to be considered.

**Comment by Daru13** [comment]
Sorry for the slow answer, and thank you for suggesting this fix/update! :)

After merging your fix, I tried updating PDF.js to the current last version (4.0.379), but it seems like they switched to ES modules starting from major version 4, which are—as far as I know—not readily compatible with the architecture of i-LaTeX's webview. However, the last release before that change, version 3.11.174, seems to work just fine. 671cae1 updates the code to use this version instead, which, indeed, does not seem to instantiate any `Buffer` object using `new`.
